profile_name: PVGC2

exclude_internal_standard: true

exclude_ni: false

c23_tag_factor: 1.0037

density: 0.69663

report_order:

  - "C4:0"
  - "C6:0"
  - "C8:0"
  - "C10:0"
  - "C11:0"
  - "C12:0"
  - "C13:0"
  - "C14:0"
  - "C14:1"
  - "C15:0"
  - "C15:1"
  - "C16:0"
  - "C16:1"
  - "C16:2n4"
  - "C17:0"
  - "C16:3n4"
  - "C17:1"
  - "C16:4n1"
  - "C18:0"
  - "C18:1n9"
  - "C18:1n9t"
  - "C18:1n7"
  - "C18:2n6"
  - "C18:2n6t"
  - "C18:2n4"
  - "C18:3n6"
  - "C18:3n4"
  - "C18:3n3"
  - "C18:4n3"
  - "C20:0"
  - "C20:1n11+"
  - "C20:1n9"
  - "C20:2n6"
  - "C20:3n6"
  - "C21:0"
  - "C20:4n6"
  - "C20:3n3"
  - "C20:4n3"
  - "C20:5n3"
  - "C22:0"
  - "C22:1n9"
  - "C22:2n6"
  - "C23:0"
  - "C21:5n3"
  - "C22:5n6"
  - "C22:5n3"
  - "C24:0"
  - "C22:6n3"
  - "C24:1"
  - "Unknow"

aliases: {}